

import json
import csv
import subprocess

usernames = [
    "diimarino",
    "riotters",
    "Fireart-d",
    "BalkanBrothers",
    "Huemachine",
    "vian_puameno",
    "samoil-radinski",
    "studioMUTI",
    "encodedots",
    "AkshayHooda",
    "halolab",
    "DKNG",
    "ronasit",
    "Nixtio",
    "Maryam_mi",
    "DjordjeMojsilovic",
    "zhenyaartemjev",
    "Webshocker",
    "arounda",
    "acampion",
    "RonDesignLab",
    "agencyuprock",
    "dominiqueramseyart",
    "LenaBereshchuk",
    "Ahmedcreatives",
    "solar-digital",
    "makers_co",
    "piqostudio",
    "SavaStoic",
    "AnnSophieDeSteur",
    "Fireart-d",
    "karliingersoll",
    "gilhuybrecht",
    "Stevan",
    "kreyda",
    "studioMUTI",
    "alty",
    "vektora",
    "immersivestudios",
    "jerzyzareba",
    "redis_agency",
    "maimun88",
    "Gerdoo_cartoon",
    "matthieumartigny",
    "orixcreative",
    "mockup-cloud",
    "nadira",
    "romanklco",
    "Jaysx1",
    "KatrinEmery",
    "JordonCheung",
    "dominiqueramseyart",
    "prosymbols",
    "juzuco",
    "GeexArts",
    "Folio",
    "Kickin",
    "DarwinApps",
    "ajdin",
    "DrawingArt",
    "artonestdesign",
    "ibrahimquayum",
    "Brightlab",
    "tapeshmalik",
    "Tubik",
    "thecamiloes",
    "randhir051",
    "denysnichele",
    "JackGunns",
    "limkangli",
    "weareillustrationx",
    "stas_kulesh",
    "Kimko_design",
    "tommychandra",
    "lothar1410",
    "kravetzzz",
    "tamoona",
    "forsureletters",
    "23k23k23",
    "roohollah",
    "RazvanVezeteu",
    "azizulhaque96",
    "laingroup",
    "alev_studio",
    "brasshands",
    "sizoriton",
    "zaeemnaveed",
    "khltrn",
    "Lada_Daria",
    "H_Todd",
    "Comscreen",
    "James_3D_Arts",
    "MadeByLisaMarie",
    "dinidumissaka",
    "LivelyScout",
    "agensip",
    "Champuchinito",
    "Neekah",
    "dstudiotech",
    "Greg_Grigoriou",
    "karliingersoll",
    "GTDesign7",
    "limkangli",
    "MateMiminoshvili",
    "dominiqueramseyart",
    "gildamartini",
    "Conceptzilla",
    "IgorSkyNet",
    "tubik_arts",
    "Nozaracy",
    "zettxh",
    "james-alonso",
    "atomicvibe",
    "reijo",
    "lillyzach",
    "caviaragency",
    "ufukyilmaz",
    "lillianpham_",
    "H_Todd",
    "finetuneco",
    "nick_studio",
    "kadyjesko",
    "Kaisam",
    "Fran6",
    "Champuchinito",
    "ThomasJCarter",
    "d-studio",
    "roberlan",
    "CameronKimJones",
    "anuraveendran",
    "rokasaleliunas",
    "jannatulferdousi7",
    "CourtneyGosserDesign",
    "alejandro_plaza",
    "menainizar",
    "MorissetteYan",
    "ace_ace",
    "ronasit",
    "Dulaas",
    "viktorhanacek",
    "KenSmithCreative",
    "metinseven",
    "yeganehaubi",
    "jan_hala",
    "lillianpham_",
    "RKBDI",
    "CameronKimJones",
    "Ota_skvor",
    "AnnaSzeleszczyk",
    "OneSevenTech",
    "dominiqueramseyart",
    "NicholasRoberts",
    "designedbymiya",
    "alexandersha",
    "thinkflagship",
    "MOSAIKO",
    "imesaros",
    "OneSevenTech",
    "Avantika_2006",
    "pmroz",
    "sleeplessmedia",
    "CameronKimJones",
    "mdsajib3",
    "menainizar",
    "richard_carpenter",
    "Esli",
    "erodgers",
    "madcritter1122",
    "styblova",
    "brewdo_design",
    "zahidvector",
    "MilenaKo",
    "RyanCrisman",
    "olymp",
    "AushaCo",
    "lillianpham_",
    "dominiqueramseyart",
    "stas_kolesnik",
    "vickimaiden",
    "acampion",
    "MorissetteYan",
    "Imoogigraphic",
    "i_meskhi",
    "OWWStudio",
    "marylu",
    "kravetzzz",
    "melibelenr",
    "NedaIvanova",
    "wewillfancy",
    "yumansdesign",
    "MOSAIKO",
    "Mimaagency",
    "pmroz",
    "gildamartini",
    "OmkarXChavan",
    "RetrospectiveMedia",
    "walwaalemayehu096193",
    "paulmullen",
    "Gerdoo_cartoon",
    "gildamartini",
    "arshreeram",
    "Timber",
    "styblova",
    "brewdo_design",
    "FHSolutions",
    "RonDesignLab",
    "kalynasolutions",
    "olymp",
    "jinaprjct",
    "lillianpham_",
    "netlalab",
    "sahil_dobariya",
    "sizoriton",
    "FasterThanLight",
    "Whales_of_Design",
    "gildamartini",
    "DesignEssense",
    "makethegrade",
    "RetrospectiveMedia",
    "MemoryLane",
    "mindeanimates",
    "Type08",
    "designbeaker",
    "gildamartini",
    "buraqlab",
    "pmroz",
    "pmroz",
    "lillianpham_",
    "BalkanBrothers",
    "design-studio",
    "vask",
    "Shamimhaque",
    "atomicvibe",
    "RetrospectiveMedia",
    "wahabapple",
    "lillianpham_",
    "almigor",
    "Lenuge",
    "brasshands",
    "Benoit_Drigny",
    "orixcreative",
    "dolphinwebsol",
    "pmroz",
    "Kakhadzen",
    "MBD",
    "forsureletters",
    "vaneltia",
    "Tubik",
    "pmroz",
    "FATEMA_F",
    "laingroup",
    "dellacolletta",
    "lillianpham_",
    "novacluster",
    "JuliaTillery",
    "chaseestes",
    "MdSidurRahman",
    "nikolaobradovic",
    "alekayami",
    "isaacleon",
    "zoriadesign",
    "AnnaSzeleszczyk",
    "pixavailstudio",
    "spencergabor",
    "EmiraRazic",
    "dmitrykavalev",
    "gildamartini",
    "_gracepedersen",
    "DropkickStudio",
    "Flinzpa",
    "pmroz",
    "theonlymark",
    "jonesandcompany",
    "taniatania_art",
    "AliGiroux",
    "brittainhicks",
    "nick_studio",
    "pmroz",
    "Mustacich",
    "kylinnrich",
    "ivanpavllenko",
    "tubik_arts",
    "eagoodrow",
    "chaseestes",
    "IagoHerc",
    "Oyay",
    "_gracepedersen",
    "zht",
    "Nozaracy",
    "DSGN89",
    "ShakuroGraphics",
    "rdutch",
    "gildamartini",
    "anastasia-tino",
    "mikewaite",
    "lontongDesign",
    "SorenSelleslagh",
    "marylu",
    "MOSAIKO",
    "welldux",
    "firajibgd",
    "glebich",
    "pmroz",
    "kseniia_puzrova",
    "Champuchinito",
    "fofodwill",
    "Cuneytsens",
    "pmroz",
    "teresa_chylinska_kur",
    "chaseestes",
    "roberlan",
    "Nixtio",
    "studioMUTI",
    "awsmd",
    "GeexArts",
    "santedesign",
    "intudio",
    "pmroz",
    "nileshthorath",
    "Jazminkatz",
    "lillianpham_",
    "Jubayer85",
    "Ale-xan-dra",
    "reijo",
    "liashaffer",
    "gildamartini",
    "forwwward",
    "JLDesign313",
    "thinkflagship",
    "brewdo_design",
    "MdSidurRahman",
    "qclay",
    "Champuchinito",
    "WiesiaRuta"
]

# Function to run the drbl_py command and save output to a JSON file
def run_drbl_py(username):
    json_file_path = f'{username}.json'
    # Example command, replace with your actual command and ensure it saves the output to a JSON file
    command = f'drbl_py -u {username}'
    subprocess.run(command, shell=True)
    return json_file_path

# Process a single JSON file and return the data to be added to the CSV
def process_json_file(json_file_path):
    try:
        with open(json_file_path, 'r') as file:
            data = json.load(file)
        # Extract and process user data from JSON
        user_description = data.get('user_description', '')
        bio = data.get('bio', '')
        skills = ', '.join(data.get('skills', []))
        collections = data.get('collections', {})
        portfolio_items = []
        for collection_name, collection_details in collections.items():
            for title, details in collection_details.get('shots', {}).items():
                shot_url = details.get('shot_url', '')
                if '?resize=400x0' in shot_url:
                    shot_url = shot_url.split('?resize=400x0')[0]
                    portfolio_items.append({'title': title.strip(), 'shot_url': shot_url})
        return {
            'description': user_description,
            'bio': bio,
            'skills': skills,
            'portfolio_items': json.dumps(portfolio_items)  # Convert the list of dicts to a JSON string
        }
        


    except FileNotFoundError:
        print(f"File not found: {json_file_path}. Skipping...")
        return None  # Return None to indicate the file was not processed

# CSV file setup
csv_file_path = 'user_portfolio_with_details.csv'
fieldnames = ['description', 'bio', 'skills', 'portfolio_items']

with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    
    for username in usernames:
        json_file_path = run_drbl_py(username)
        user_data = process_json_file(json_file_path)
        if user_data:  # Only write to CSV if user_data is not None
            writer.writerow(user_data)

            # move the json file to a folder called 'json_files'
            subprocess.run(f'mv {json_file_path} json_files/', shell=True)
            print(f'User data for {username} has been processed and added to the CSV file.')
        else:
            print(f'User data for {username} could not be processed.')

print('CSV file with user details and portfolio items has been created successfully.')



